-- MySQL Script generated by MySQL Workbench
-- Сб 01 дек 2018 13:35:20
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema osint
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema osint
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `osint` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `osint` ;

-- -----------------------------------------------------
-- Table `auto_model`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `auto_model` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `auto_model` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `model_name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `auto_modif`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `auto_modif` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `auto_modif` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `auto_modifcol` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `auto_year`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `auto_year` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `auto_year` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `auto_yearcol` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `auto_kpp`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `auto_kpp` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `auto_kpp` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `auto_kppcol` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `auto_dvs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `auto_dvs` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `auto_dvs` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `auto_dvscol` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `auto_own`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `auto_own` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `auto_own` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `auto_owncol` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `auto_exchange`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `auto_exchange` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `auto_exchange` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `auto_exchangecol` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `auto_status`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `auto_status` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `auto_status` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `auto_statuscol` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `auto_condition`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `auto_condition` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `auto_condition` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `auto_conditioncol` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `auto_body`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `auto_body` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `auto_body` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `auto_bodycol` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `auto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `auto` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `auto` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `auto_model_id` INT NOT NULL,
  `auto_modif_id` INT NOT NULL,
  `auto_year_id` INT NOT NULL,
  `auto_kpp_id` INT NOT NULL,
  `auto_dvs_id` INT NOT NULL,
  `auto_own_id` INT NOT NULL,
  `auto_exchange_id` INT NOT NULL,
  `auto_status_id` INT NOT NULL,
  `auto_condition_id` INT NOT NULL,
  `phone_id` INT NOT NULL,
  `dict_rudder_id` INT NOT NULL,
  `auto_body_id` INT NOT NULL,
  `avito_avtor_name_id` INT NOT NULL,
  `probeg` VARCHAR(100) NULL,
  `sell` VARCHAR(100) NULL,
  `avito_sity_id` INT NOT NULL,
  PRIMARY KEY (`id`, `auto_model_id`, `auto_modif_id`, `auto_year_id`, `auto_kpp_id`, `auto_dvs_id`, `auto_own_id`, `auto_exchange_id`, `auto_status_id`, `auto_condition_id`, `phone_id`, `dict_rudder_id`, `auto_body_id`, `avito_avtor_name_id`, `avito_sity_id`))
ENGINE = InnoDB;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
