-- MySQL Script generated by MySQL Workbench
-- Вс 18 ноя 2018 15:24:41
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema osint
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `osint` ;

-- -----------------------------------------------------
-- Schema osint
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `osint` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `osint` ;

-- -----------------------------------------------------
-- Table `avito_avtor_name`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `avito_avtor_name` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `avito_avtor_name` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `dict_version_avto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dict_version_avto` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `dict_version_avto` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin
COMMENT = 'тип кузова';

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `dict_type_dvs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dict_type_dvs` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `dict_type_dvs` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin
COMMENT = 'тип двигателя';

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `dict_actuator`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dict_actuator` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `dict_actuator` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin
COMMENT = 'тип привода';

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `dict_body_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dict_body_type` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `dict_body_type` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin
COMMENT = 'тип кузова';

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `dict_rudder`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dict_rudder` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `dict_rudder` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin
COMMENT = 'руль';

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `avito_name_avto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `avito_name_avto` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `avito_name_avto` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `model` VARCHAR(45) NULL COMMENT 'модель',
  `year_of_manufacture` INT NULL COMMENT 'год выпуска',
  `version` INT NULL COMMENT 'модификация',
  `type` INT NULL COMMENT 'тип двигателя',
  `actuator` INT NULL COMMENT 'привод',
  `body_type` INT NULL COMMENT 'тип кузова',
  `rudder` VARCHAR(45) NULL COMMENT 'руль',
  `dict_version_avto_id` INT NOT NULL,
  `dict_type_dvs_id` INT NOT NULL,
  `dict_actuator_id` INT NOT NULL,
  `dict_body_type_id` INT NOT NULL,
  `dict_rudder_id` INT NOT NULL,
  PRIMARY KEY (`id`, `dict_version_avto_id`, `dict_type_dvs_id`, `dict_actuator_id`, `dict_body_type_id`, `dict_rudder_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `avito_sity`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `avito_sity` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `avito_sity` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `sity_name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `phone`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `phone` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `phone` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `phone_number` INT(20) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin
COMMENT = 'таблица хранения телефонов';

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `avito_avto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `avito_avto` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `avito_avto` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT 'id',
  `id_avto` INT NULL COMMENT 'идентификатор машины',
  `mileage` VARCHAR(45) NULL COMMENT 'пробег',
  `color` INT NULL COMMENT 'цвет',
  `status` VARCHAR(45) NULL COMMENT 'состояние',
  `price` VARCHAR(45) NULL COMMENT 'цена',
  `owner` INT NULL COMMENT 'владелец',
  `sity` INT NULL COMMENT 'город',
  `phone_number` INT NULL COMMENT 'номер телефона',
  `link_ad` VARCHAR(500) NULL COMMENT 'ссылка на объявление',
  `date` VARCHAR(45) NULL,
  `source` VARCHAR(45) NULL COMMENT 'источник поступления',
  `avito_avtor_name_id` INT NOT NULL,
  `avito_name_avto_id` INT NOT NULL,
  `avito_sity_id` INT NOT NULL,
  `phone_id` INT NOT NULL,
  PRIMARY KEY (`id`, `avito_avtor_name_id`, `avito_name_avto_id`, `avito_sity_id`, `phone_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `dict_load_file`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dict_load_file` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `dict_load_file` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `status` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin
COMMENT = 'состояние загруженных файлов';

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `source`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `source` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `source` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `source` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin
COMMENT = 'источник поступления информации';

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `loadd_file`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `loadd_file` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `loadd_file` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NULL,
  `status` INT NULL,
  `load_info` INT(6) NULL,
  `errors` INT(6) NULL,
  `staream` INT(3) NULL,
  `source` INT NULL,
  `dict_load_file_id` INT NOT NULL,
  `source_id` INT NOT NULL,
  PRIMARY KEY (`id`, `dict_load_file_id`, `source_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin
COMMENT = 'полученные файлы';

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `login_users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `login_users` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `login_users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `login_name` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `first_name` VARCHAR(45) NULL,
  `last_name` VARCHAR(45) NULL,
  `role` INT NULL,
  `group` INT NULL,
  `ip_create` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin
COMMENT = 'авторизация пользователей';

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `avito_other`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `avito_other` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `avito_other` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `text` VARCHAR(500) NULL,
  `price` VARCHAR(45) NULL,
  `owner` INT NOT NULL,
  `sity` INT NOT NULL,
  `phone_number` INT NOT NULL,
  `link_ad` VARCHAR(45) NOT NULL,
  `avito_avtor_name_id` INT NOT NULL,
  `avito_sity_id` INT NOT NULL,
  `phone_id` INT NOT NULL,
  PRIMARY KEY (`id`, `avito_avtor_name_id`, `avito_sity_id`, `phone_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin
COMMENT = 'авито остальное';

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `dict_load_file`
-- -----------------------------------------------------
START TRANSACTION;
USE `osint`;
INSERT INTO `dict_load_file` (`id`, `name`, `status`) VALUES (1, '1', получена информация);
INSERT INTO `dict_load_file` (`id`, `name`, `status`) VALUES (2, '2', поставлен в очередь);
INSERT INTO `dict_load_file` (`id`, `name`, `status`) VALUES (3, '3', залит в БД);

COMMIT;


-- -----------------------------------------------------
-- Data for table `source`
-- -----------------------------------------------------
START TRANSACTION;
USE `osint`;
INSERT INTO `source` (`id`, `source`) VALUES (1, 'авито авто');
INSERT INTO `source` (`id`, `source`) VALUES (2, 'авито остальное');

COMMIT;


-- -----------------------------------------------------
-- Data for table `login_users`
-- -----------------------------------------------------
START TRANSACTION;
USE `osint`;
INSERT INTO `login_users` (`id`, `login_name`, `password`, `first_name`, `last_name`, `role`, `group`, `ip_create`) VALUES (1, 'admin', NULL, 'admin', 'admin', 1, 1, 1);

COMMIT;

