-- MySQL Script generated by MySQL Workbench
-- Сб 08 дек 2018 15:55:20
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema osint
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema osint
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `osint` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `osint` ;

-- -----------------------------------------------------
-- Table `vk_other`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vk_other` (
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mail`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mail` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `vk_parser`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vk_parser` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(500) NULL,
  `last_name` VARCHAR(500) NULL,
  `password` VARCHAR(45) NULL,
  `user_id` VARCHAR(45) NULL,
  `phone_id` INT NOT NULL,
  `vk_other_id` INT NOT NULL,
  `mail_id` INT NOT NULL,
  PRIMARY KEY (`id`, `phone_id`, `vk_other_id`, `mail_id`))
ENGINE = InnoDB;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
