-- MySQL Script generated by MySQL Workbench
-- Ср 28 ноя 2018 20:02:41
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema osint
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema osint
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `osint` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `osint` ;

-- -----------------------------------------------------
-- Table `avito_catalog`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `avito_catalog` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `avito_catalog` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `catalog_name` VARCHAR(100) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `avito_other`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `avito_other` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `avito_other` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `price` VARCHAR(70) NULL,
  `avito_avtor_name_id` INT NOT NULL,
  `avito_sity_id` INT NOT NULL,
  `phone_id` INT NOT NULL,
  `avito_catalog_idavito_catalog` INT NOT NULL,
  `link_ad` VARCHAR(200) NULL,
  PRIMARY KEY (`id`, `avito_avtor_name_id`, `avito_sity_id`, `phone_id`, `avito_catalog_idavito_catalog`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin
COMMENT = 'авито остальное';

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
